[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt && chmod +x start.sh"

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[metrics]
port = 8000
path = "/"

[http]
requestTimeout = 300    # 5 minutes
readHeaderTimeout = 60  # 1 minute
idleTimeout = 300       # 5 minutes 